apiVersion: v1
kind: ConfigMap
metadata:
  name: mongosqld-config
data:
  config.yaml: |
    {{- $mergedConfig := mergeOverwrite .Values.mongosqldConfigDefault .Values.mongosqldConfig }}
{{ $mergedConfig | toYaml | indent 4 }}
