
base:
  replicaCount: 1

  image:
    repository: dasmeta/mongodb-bi-connector
    pullPolicy: IfNotPresent
    tag: 1.0.3

  containerPort: 3307
  service:
    type: ClusterIP
    port: 3307

  deployment:
    volumes:
      - mountPath: /home/mongobi/mongodb-bi-linux-x86_64-ubuntu1804-v2.14.5/mongosqld
        name: config
        configMap:
          name: mongosqld-config
        readOnly: true

mongosqldConfig:

mongosqldConfigDefault:
  net:
    bindIp: "0.0.0.0" # To bind to multiple IP addresses, enter a list of comma separated values.
    port: 3307
    # unixDomainSocket:
    #   enabled: false
    #   pathPrefix: "/var"
    #   filePermissions: "0600"
    ssl:
      # mode: "disabled"
      # allowInvalidCertificates: false
      # PEMKeyFile: <string>
      # PEMKeyPassword: <string>
      # CAFile: <string>
      # minimumTLSVersion: TLS1_1
    ssl:
      mode: 'requireSSL'
      PEMKeyFile: './certs/bi.pem'
      CAFile: './certs/mdbca.crt'
  mongodb:
    net:
      uri: mongodb://mongodb
      auth:
        username: root
        password: password
        source: admin
        mechanism: "SCRAM-SHA-1"
  # Security options - configure mongosqld's authentication (disabled by default).
  ## Enable security options if your MongoDB cluster requires authentication.
  ## https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#security-options
  security:
    enabled: true
  #   defaultMechanism: "SCRAM-SHA-1"
  #   defaultSource: "admin"
  #   gssapi:
  #     hostname: <string>
  #     serviceName: "mongosql"
  ## Logging options
  ## https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#logging-options
  systemLog:
    ## The path to the file where log output will be written to.
    ## Defaults to stderr.
    path: ./mongosql.log
    quiet: false
    ## 0|1|2 - Verbosity of the log output, this is overridden if `quiet` is true.
    verbosity: 2
    logAppend: true
  #logRotate: "rename" # "rename"|"reopen"
  ## Schema options
  ## These configuration options define how the mongosqld should sample your MongoDB
  ## data so that it can be used by the relational application.
  ## https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#data-sampling-options
  schema:
    ## If you've generated a DRDL schema file using mongodrdl, you can supply the
    ## path for mongosqld to use that schema DRDL file.
    # path: <string>
    # maxVarcharLength: <integer>
    ## Use the `refreshIntervalSecs` option to specify an interval in seconds for
    ## mongosqld to update its schema, either by resampling or by re-reading from
    ## the schema source. The default value for this option is 0, which means that
    ## mongosqld does not automatically refresh the schema after it is
    ## initialized.
    refreshIntervalSecs: 0
    #stored:
    #  mode: "custom" # "auto"|"custom"
    #  source: "mongosqld_data" # the database where schemas are stored in stored-schema modes
    #  name: "mySchema" # the named schema to read/write to in stored-schema modes
    sample:
      size: 1000 # The amount of random documents we sample from each collection.
      namespaces: ["*.*"]
      # prejoin: false
      # uuidSubtype3Encoding: "old" # <[old|csharp|java]>
  ## Process management options
  ## https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#process-management-options
  processManagement:
    service:
      name: "mongosql"
      displayName: "MongoSQL Service"
      description: "MongoSQL accesses MongoDB data with SQL"
