jobs:
  - name: cronjob1
    schedule: "0 * * * *"
    restartPolicy: OnFailure
    image:
      registry: docker.io
      repository: busybox
      pullPolicy: IfNotPresent
      tag: latest
    env:
      - name: key3
        value: value3
      - name: key4
        value: value4
    volumes: {}
#      - name: persistent-storage
#        mountPath: /path
#        persistentVolumeClaim:
#          claimName: claim
    storage: {}
#      persistentVolumeClaimName: claim
#      accessModes:
#        - ReadWriteMany
#      className: claim
#      requestedSize: 5Gi
#      enableDataSource: false

  - name: cronjob2
    schedule: "* * * * *"
    restartPolicy: OnFailure
    image:
      registry: docker.io
      repository: busybox
      pullPolicy: IfNotPresent
      tag: latest
    env:
      - name: key3
        value: value3
      - name: key4
        value: value4
    volumes: {}
#      - name: persistent-storage
#        mountPath: /path
#        persistentVolumeClaim:
#          claimName: claim
    storage: {}
#      persistentVolumeClaimName: claim
#      accessModes:
#        - ReadWriteMany
#      className: efs-sc
#      requestedSize: 5Gi
#      enableDataSource: false
