{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8up.fullname" . }}
  labels:
    {{- include "k8up.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8up.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "k8up.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
