name: Release helm chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run Release
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Create gZip
        run: |
          tar czf helm-chart-test-1.2.tgz charts/
          git add helm-chart-test-1.2.tgz
          git commit -m "zip file commit"
          git push
      - name: Helm Update
        run: |          
          helm repo index .
          git add index.yaml
          git commit -m "index file commit"
          git push
