{{- range $job := .Values.jobs }}
{{- $registry := $job.image.registry }}
{{- $tag := $job.image.tag }}
{{- $image := print $registry "/" $job.image.repository ":" $tag }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $job.name | quote}}
spec:
  schedule: {{ $job.schedule | quote}}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ $job.serviceAccountName }}
          restartPolicy: {{ $job.restartPolicy }}
          containers:
            - name: {{ $job.name | quote }}
              image: {{ $image | quote}}
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: {{ $job.resources.request.cpu }}
                  memory: {{ $job.resources.request.memory }}
                limits:
                  cpu: {{ $job.resources.limits.cpu }}
                  memory: {{ $job.resources.limits.memory }}
              command: {{ $job.command }}
              env:
              {{- range $env := $job.env }}
                - name: {{ $env.name | quote}}
                  value: {{ $env.value | quote }}
              {{- end }}
              volumeMounts:
            {{- range $index, $element := $job.volumes }}
                - name: {{ coalesce $element.name (add $index 1) }}
                  mountPath: {{ $element.mountPath }}
                  readOnly: {{ $element.readOnly | default false }}
            {{- end }}
      {{- if $job.volumes }}
          volumes:
        {{- range $index, $element := $job.volumes }}
            - name: {{ coalesce $element.name (add $index 1) }}
          {{- if $element.persistentVolumeClaim }}
              persistentVolumeClaim:
            {{- if $element.persistentVolumeClaim.claimName }}
                claimName: {{ $element.persistentVolumeClaim.claimName }}
            {{- end }}
          {{- end }}
          {{- end }}
{{- end }}
{{- end }}
---
